### ISSUE TITLE
Generators

### ISSUE THREAD

**Issue by k-ode** [ConrabOpto/mst-query#14]
Would be nice to build model generators based on backend schemas like graphql. We should be able to use something similar to what is being used in `mst-gql`.

Generating models should mostly just work, but I'm curious if we could also generate stores/queries/mutations?

**Comment by k-ode** [comment]
We now have a graphql generator.

**Comment by k-ode** [comment]
@beepsoft The issue text says as much :)

This library started out as a fork of mst-gql. The generator is also based on the one in mst-gql, but is completely re-written in typescript.

**Comment by beepsoft** [comment]
@k-ode Sorry, I missed that. :-) mst-gql's generator is a bit outdated, so, do you think it would be possible to somehow port back your generator there? I see, for example, that you have less generator options, but the overall generated models seems to be quite the same.
