### ISSUE TITLE
How to use it with Nextjs?

### ISSUE THREAD

**Issue by benjaminkwokhuen** [ConrabOpto/mst-query#17]
Got ```SyntaxError: Cannot use import statement outside a module```

The module does not work in server side.

**Comment by k-ode** [comment]
This is becuase nextjs doesn't support esm modules properly yet. See this thread and comment: https://github.com/vercel/next.js/issues/9890#issuecomment-968365119

The solution is to use `next-transpile-modules` in your next.config.js.

```js
const withTM = require('next-transpile-modules')(['mst-query']);

module.exports = withTM({
  ... 
});
```

**Comment by benjaminkwokhuen** [comment]
@k-ode Thanks a lot. It works now.
