### ISSUE TITLE
Anyway to access the rootStore without using context / useRootstore hook

### ISSUE THREAD

**Issue by geohuz** [ConrabOpto/mst-query#40]
In react-router v6 there is a data router which expose function ``action/loader`` calls fetch api, but these functions are out of component scope, I'm wondering how can I reference the rootStore from the normal function?

**Comment by k-ode** [comment]
Yes, you can initialize the query client manually.

```ts
export const queryClient = new QueryClient({ RootStore });
queryClient.init(initialData, env); // internally calls RootStore.create(initialData, env)
const rootStore = queryClient.rootStore;
```

**Comment by geohuz** [comment]
@k-ode thanks! That's fair enough.
