### ISSUE TITLE
Question on usage of single record model

### ISSUE THREAD

**Issue by geohuz** [ConrabOpto/mst-query#41]
I need to create a store which has a model contains single record: {token: "...."}, which is:

```js
const AuthModel = types.model("AuthModel", {
  token: optional(string, "none")
})
```

to execute the login api(a post method), I have the following mutation:

```js
const Login = createMutation('Login', {
  request: types.model({email: "", pass: ""}),
})
```

I need to use the result of the login mutation to populate the AuthModel, so I finally wrote the AuthModel as below (without creating a store):

```js
const AuthModel = types.model("AuthModel", {
  token: optional(string, "none")
})
.props({
    login: optional(Login, {})
  })
  .actions(self=> ({
    loginUser: flow(function* (request) {
      const qry = yield* self.login.mutate({
        endpoint: api.login,
        request: request
      })
      let result = qry()
      self.token = self.login.data?.token
      return result
    })
  }))
```

then the rootStore:

```js
export const RootStore = createRootStore({
  auth: optional(AuthModel, {})
})
```

and lastly I can use the token in the ``rootStore.auth.token``, while it works but I'm not sure if I understand correctly or there is a better way to structure the data model as above. (A single record model)

**Comment by k-ode** [comment]
It's perfectly valid to use non-identifier models as data types for mutations and queries. The difference is that you don't need to use `MstQueryRef` or `createModelStore` for these, as they will not get normalized.

For things like Auth, I like to call the models `services`.

```ts
const AuthModel = types.model("AuthModel", {
  token: optional(string, "none")
})

const Login = createMutation('Login', {
  data: AuthModel,
  request: types.model({email: "", pass: ""}),
})

const AuthService = types.model("AuthService", {
    login: optional(Login, {})
  })
  .views(self => ({
    get token() {
      return self.login.data?.token;
     }
  }))
  .actions(self=> ({
    loginUser: flow(function* (request) {
      const qry = yield* self.login.mutate({
        endpoint: api.login,
        request: request
      })
      let result = qry()
      return result
    })
  }))

const RootStore = createRootStore({
  authService: optional(AuthService, {})
})
```

**Comment by geohuz** [comment]
@k-ode  Thanks for the answer!  Now I have more understanding on the mst-query, I have one more question: when I access the ``rootStore.authService.token`` for the first time it is ``undefined``,  it is possible to init the model to "none"? Or I just put some logic in the ``get token()`` view to return "none"?

**Comment by k-ode** [comment]
Yes, i would put "none" as a default value in a view in this case. The data property is really what you get from the server.

**Comment by geohuz** [comment]
@k-ode Ok, I got it.
