### ISSUE TITLE
QueryClientProvider error with React 18. Type '{ children: Element; }' has no properties in common

### ISSUE THREAD

**Issue by ericklombardo** [ConrabOpto/mst-query#42]
I have the following error using react 18

TS2559: Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & QueryClientProviderProps.

For a temporary fix i am doing the following:

Redeclaring the type QueryClientProviderProps and include the children prop

```
declare type QueryClientProviderProps = {
  env?: any;
  initialData?: any;
  children: React.ReactNode;
};

```

Then in my code export the QueryClientProvider with the new type defined above

```
export QueryClientProvider const QueryClientProvider: FC<QueryClientProviderProps> = context.QueryClientProvider;
```

**Comment by k-ode** [comment]
Fixed in 2.0.7
