### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/mst-query.js?v=75f07253' does not provide an export named 'MstQueryRef'

### ISSUE THREAD

**Issue by geohuz** [ConrabOpto/mst-query#46]
version :  "mst-query": "^3.0.3",
I'm using vite.js,  the import works with version 2.0.4

**Comment by k-ode** [comment]
We just released a new major version of this library, where MstQueryRef is no longer needed. You can just use normal mobx-state-tree `types.reference`.
