### ISSUE TITLE
Data prop not updating for pagination

### ISSUE THREAD

**Issue by krisbot01** [ConrabOpto/mst-query#72]
I am using the same setup as the example from the README with these query options:
```
{
  pagination: { skip: skip, take: 10 },
  enabled: true,
  refetchOnChanged: "pagination"
}
```

When I update _skip_ the endpoint gets called, the data received and the _models_ map of the model-store gets updated but the data of the query remains the same. Replacing pagination with request gives me the update but that overwrites the data completely.

I've been digging through the source code and it looks like the intention is for the data to merge at some point close to the prepareData call but I am not sure where it goes wrong. 

For now I'll try to get a workaround running but this seems to be a case that is not part of the tests either.

**Edit:**
I ended up on this workaround added to the modelStore.

```
.views((self) => ({
  get data() {
    return Array.from(self.models.values())
  }
}))
```

**Comment by k-ode** [comment]
Thanks for raising this issue. I'm aiming to cut a proper release and update the documentation soon.

A new function, `onQueryMore`, has been introduced, which allows you to attach a listener to a query that's triggered whenever more data is fetched. There's no default behavior for adding data because it's unclear whether you prefer to append or prepend the data to your list.

```tsx
export const ItemListQuery = createQuery('ItemListQuery', {
    data: t.model({
        items: t.array(ItemModel),
    }),
    pagination: t.model({
        skip: 0,
    }),
}).actions((self) => ({
    afterCreate() {
        onQueryMore(self, (data) => {
            self.data.items.push(...data.items);
        });
    },
}));

```

**Comment by k-ode** [comment]
In v4, this has hopefully changed to be more intuitive:

```ts
const ItemListQuery = createInfiniteQuery('ItemListQuery', {
    data: t.model({
        items: t.array(ItemModel),
    }),
    pagination: t.model({
        skip: 0,
    }),
    onQueryMore({ data, query } {
       query.data.items.push(...data.items);
    });
});

useInfiniteQuery(store.itemListQuery, {
   pagination: { skip }
});
```
